set(OBJ_SRC
${SRC_OBJ_PATH}/botobject.cpp
${SRC_OBJ_PATH}/botmembership.cpp
${SRC_OBJ_PATH}/botmessage.cpp
${SRC_OBJ_PATH}/botpeople.cpp
${SRC_OBJ_PATH}/botwebhook.cpp
${SRC_OBJ_PATH}/botroom.cpp
${SRC_OBJ_PATH}/botstore.cpp
)

set(OBJ_HEAD
${SRC_OBJ_PATH}/botobject.h
${SRC_OBJ_PATH}/botmembership.h
${SRC_OBJ_PATH}/botmessage.h
${SRC_OBJ_PATH}/botpeople.h
${SRC_OBJ_PATH}/botwebhook.h
${SRC_OBJ_PATH}/botroom.h
${SRC_OBJ_PATH}/botstore.h
)
